#pragma once

#define ICON_FILE "terminal-tango.svg"
#define SCROLL_LINES 4096
#define DEFAULT_SCROLL_LINES 4096
#define HTTP_REGEXP "(ftp|http)s?://[^ \t\n\b()<>{}«»\\[\\]\'\"]+[^.]"
#define MAIL_REGEXP "[^ \t\n\b]+@([^ \t\n\b]+\\.)+([a-zA-Z]{2,4})"
#define DEFAULT_CONFIGFILE "ume.conf"
#define DEFAULT_COLUMNS 80
#define DEFAULT_ROWS 24
#define DEFAULT_FONT "Ubuntu Mono,monospace 12"
#define FONT_MINIMAL_SIZE (PANGO_SCALE * 6)
#define DEFAULT_WORD_CHARS "-,./?%&#_~:"
#define DEFAULT_PALETTE "solarized_dark"
#define TAB_MAX_SIZE 40
#define TAB_MIN_SIZE 6
#define FORWARD 1
#define BACKWARDS 2
#define FADE_PERCENT 10
#define DEFAULT_ADD_TAB_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_DEL_TAB_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_SWITCH_TAB_ACCELERATOR (GDK_CONTROL_MASK)
#define DEFAULT_MOVE_TAB_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_COPY_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_SCROLLBAR_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_OPEN_URL_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_FONT_SIZE_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_SET_TAB_NAME_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_SEARCH_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_SELECT_COLORSET_ACCELERATOR (GDK_CONTROL_MASK | GDK_SHIFT_MASK)
#define DEFAULT_ADD_TAB_KEY GDK_KEY_T
#define DEFAULT_DEL_TAB_KEY GDK_KEY_W
#define DEFAULT_PREV_TAB_KEY GDK_KEY_Left
#define DEFAULT_NEXT_TAB_KEY GDK_KEY_Right
#define DEFAULT_COPY_KEY GDK_KEY_C
#define DEFAULT_PASTE_KEY GDK_KEY_V

#define DEFAULT_SCROLLBAR_KEY GDK_KEY_S

#define DEFAULT_SCROLL_UP_KEY GDK_KEY_K
#define DEFAULT_SCROLL_DOWN_KEY GDK_KEY_J
#define DEFAULT_SCROLL_PAGE_UP_KEY GDK_KEY_U
#define DEFAULT_SCROLL_PAGE_DOWN_KEY GDK_KEY_D
#define DEFAULT_SCROLL_AMOUNT 10

#define DEFAULT_SET_TAB_NAME_KEY GDK_KEY_N
#define DEFAULT_SEARCH_KEY GDK_KEY_F
#define DEFAULT_FULLSCREEN_KEY GDK_KEY_F11
#define DEFAULT_INCREASE_FONT_SIZE_KEY GDK_KEY_plus
#define DEFAULT_DECREASE_FONT_SIZE_KEY GDK_KEY_minus
#define DEFAULT_SCROLLABLE_TABS TRUE

#define NUM_COLORSETS 6
